######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project laDiag - DL1HBD 10.05.2007
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug
CONFIG += qt
QT += sql
QT += network

LIBS = -L/usr/lib
unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
  DEFINES-=UNICODE
  TARGET=qslprintdb
}

# -- Input --
FORMS += qslpr.ui\
         medium.ui\
         mediumText.ui

HEADERS += qslPr.h\
           medium.h\
           postFile.h\
           mediumText.h\
           translate.h

SOURCES += main.cpp\
           qslPr.cpp\
           qslPrCb.cpp\
           medium.cpp\
           postFile.cpp\
           mediumText.cpp\
           mediumTextCb.cpp\
           ../qtlogDiag/dirmngr.cpp\
           translate.cpp

RESOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/qslprintdb

DEPENDPATH +=

TRANSLATIONS += qtlogQSLlpr_en.ts
