######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project QtLog_V 0.4 - DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
#CONFIG += qt debug
CONFIG += qt
QT += network

QT += sql

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
DEFINES -= UNICODE
TARGET = admindb
}

# -- Input --
FORMS +=   admin.ui

HEADERS += admin.h \
           wadif.h

SOURCES += main.cpp \
           admin.cpp \
           adminCb.cpp \
           wadif.cpp \
           ../qtlogDiag/dirmngr.cpp

RESOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/admindb

DEPENDPATH += .
