######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project QtLog_V 0.4 - DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
#CONFIG += qt debug
CONFIG += qt

QT += sql

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

# -- Input --
FORMS +=   setup.ui

HEADERS += setup.h

SOURCES += main.cpp \
           setup.cpp \
           ../qtlogDiag/dirmngr.cpp \
           setupdata.cpp

RESOURCES = ../qtlogRessourcen.qrc

TARGET = ../setupqtlog

DEPENDPATH += .
