######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project laDiag - DL1HBD 10.05.2007
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug

CONFIG += qt
QT += sql

LIBS += -L/usr/lib

unix {
  MOC_DIR = .moc
  OBJECTS_DIR += .obj
}

# -- Input --
FORMS = ladialog.ui\

HEADERS = laDiag.h\

SOURCES += laDiag.cpp\
           laDiagDb.cpp\
           readLafiele.cpp\
           main.cpp

RESOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/ladb

DEPENDPATH =

TRANSLATIONS = qtlogLaDialog_en.ts
CODECFORTR = ISO-8859-5

