######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project addQso - 01.05.2007 DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug
CONFIG += qt
QT += sql
QT += network

VERSION = 1.5.0

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

# -- Input --
FORMS += addqso.ui \
         rigctl.ui \
         uploadR.ui

HEADERS += addQso.h \
           destination.h \
           serve.h \
           rigctl.h \
           uploadR.h

SOURCES += main.cpp \
           addQso.cpp \
           addQsoCb.cpp \
           destination.cpp \
          # ../qtlogDiag/dirmngr.cpp\
           serve.cpp \
           rigctl.cpp \
           uploadR.cpp

RESOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/addqsodb

DEPENDPATH +=

TRANSLATIONS = qtlogaddQso_en.ts
CODECFORTR = ISO-8859-5
