######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project QtLog_V 0.4 - DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug
CONFIG += qt
#QT += sql
#QT += network

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
  DEFINES -= UNICODE
  TARGET=startoptdb
}

# -- Input --
FORMS +=   start.ui

HEADERS += start.h

SOURCES += main.cpp \
           start.cpp

unix::TARGET =  ../bin/startoptdb

DEPENDPATH += .

TRANSLATIONS += qtlogStart_en.ts

