######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project laDiag - DL1HBD 10.05.2007
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug
CONFIG += qt
QT += sql

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

# -- Input --
FORMS = prefix.ui

HEADERS = prefDiag.h

SOURCES += main.cpp\
           prefDiag.cpp

RECOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/prefdb

DEPENDPATH =

TRANSLATIONS = qtlogLaPrefix_en.ts
