######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project QtLog_V 0.4 - DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug

CONFIG += qt
QT += sql
QT += network

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
  DEFINES -= UNICODE
}

# -- Input --
FORMS +=   qtlog.ui \
           configdialog.ui \
           reportlayout.ui \
           confMode.ui \
           auth.ui \
           mnote.ui \
           query.ui \
           rigctl.ui

HEADERS += Qtlog.h \
           confDiag.h \
           translate.h \
           reportLayout.h \
           qtlogdelegate.h \
           confMode.h \
           version.h \
           auth.h \
           mNote.h \
           query.h \
           quAdif.h \
           rigctl.h

SOURCES += main.cpp \
           Qtlog.cpp \
           QtlogCb.cpp \
           confDiag.cpp \
           translate.cpp \
           reportLayout.cpp \
           qtlogdelegate.cpp \
           confMode.cpp \
           auth.cpp \
           mNote.cpp \
           dirmngr.cpp \
           query.cpp \
           quAdif.cpp \
           rigctl.cpp

RESOURCES = ../qtlogRessourcen.qrc

TRANSLATIONS += qtlog_en.ts

unix::TARGET =  ../bin/qtlog

DEPENDPATH += .

OTHER_FILES += \
    qtlog_en.ts \
    qtlog_en.qm
