######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project qsl - DL1HBD 10.05.2007
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug

CONFIG += qt

QT += network  
//QT += sql

LIBS = -L/usr/lib
LIBS    += -L/usr/lib/mysql -lmysqlclient -lz -lnsl
INCLUDEPATH     += /usr/include/mysql

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
  DEFINES-=UNICODE
  TARGET=hilfedb
}


# -- Input --
FORMS += qsldb.ui

HEADERS += qsldb.h \
           dbconnection.h \
           dbresult.h \
           dbrow.h

SOURCES += main.cpp \
	   ../qtlogDiag/dirmngr.cpp \
           qsldb.cpp \
           dbconnection.cpp \
           dbresult.cpp \
           dbrow.cpp

#RESOURCES = ../qtlogRessourcen.qrc

unix::TARGET = ../bin/qslcarddb

DEPENDPATH +=

TRANSLATIONS += qtlogQSLdb_en.ts

