######################################################################
# Automatically generated by qmake (2.01a) fr. nov. 16 13:18:20 2007
######################################################################

TEMPLATE = app
LANGUAGE = C++
                 
CONFIG += qt                               
QT += network                             

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}


DEPENDPATH += .
#QT = core network


HEADERS += getmgr.h 

SOURCES += getmgr.cpp \
           main.cpp

TARGET = ../bin/getmgrdb
