######################################################################
# Automatically generated by qmake (2.01a) Di Mai 1 10:32:18 2007
# Project addQso - 01.05.2007 DL1HBD
######################################################################

TEMPLATE = app
LANGUAGE = C++

# Debug -  das bin_file wird ~12 x größer !
# CONFIG += qt debug
CONFIG += qt
QT += sql
QT += network

VERSION = 1.5.0

unix {
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

win32{
  DEFINES-=UNICODE
  TARGET = uploadEqsldbdb
}

# -- Input --


HEADERS += uploadMgr.h

SOURCES += uploadMgr.cpp \
           ../qtlogDiag/dirmngr.cpp \
           main.cpp
        
TARGET = ../bin/uploadEqsldb

DEPENDPATH +=
